//Program to refresh only the character matrix, keeping everything else intact.

#include <stdio.h>
#include <stdlib.h>
#define ROW 7
#define COL 50


//Returns the alphabetic character succeeding given character; loops back to 'a' if current character is 'z'
char next_char(char c) {
    if(c == 'z') {
        c = 'a' - 1;
    }
    c++;
    return c;
}

//Returns ascii number of random characters between 'a' and 'z', including these two
int rand_char() {
    return (rand() % ('z' - 'a' + 1)) + 'a';
}

//Prints the first type of character matrix (alphabetic)
void print_mat_1(char c) { 
    for(int i = 0; i < ROW; i++) {
        for(int j = 0; j < COL; j++) {
            printf("%c", c);
            c = next_char(c);
        }
        printf("\n");
    }
}

//Prints the second type of character matrix (random)
void print_mat_2() {
    for(int i = 0; i < ROW; i++) {
        for(int j = 0; j < COL; j++) {
            printf("%c", rand_char());
        }
        printf("\n");
    }
}

//Puts the cursor at the beginnig of the matrix
void cursor_reset() {
    printf("\x1b[s");   //Saves the current position of the cursor;
    printf("\x1b[H");   //Puts the cursor at position (1,1) in the console;
}

int main() {
    char c;
    system("clear");    //clears the entire console;

    print_mat_1('a');   //for printing a character matrix; characters are printed in alphabetic order starting from 'a';
    printf("\nHello! Hopefully this line remains unchanged throughout the program execution.\n\n");     //If the program works correctly, this line won't be affected at any time;
    
    do{
        printf("Enter 'u' to update, any other key to exit: ");     //Asking user to either update the current character matrix, or end the program;
        scanf("%c", &c);
        while(getchar() != '\n') {}     //For clearing the input buffer generated by the user during the above scanf;

        if(c != 'u') {
            return 0;
        }

        cursor_reset();     //Puts the cursor at the beginning of the character matrix in the console;
        print_mat_2();      //Prints new matrix with randomised characters ranging from 'a' to 'z'; basically overwrites the previous matrix, effectively deleting it;

        printf("\x1b[u");   //Puts the cursor back to the earlier saved position;
        printf("\x1b[1A\x1b[2K");     //Clears the entire line in which the cursor is currently present;

    }while(1);

    return 0;
}
